export const PATHS = {
  gallery: "/gallery",
  home: "/home",
  login: "/admin/login",
  contact: "/contact",
  about: "/about",
  shop: "/shop",
  news: "news",
  category: "/gallery/:category",
  serie: "/gallery/:category/:serie",
  adminOptions: "/admin/:option",
  adminEditArtwork: "/admin/edit-artwork",
  adminEditSeries: "/admin/edit-series",
  adminEditHomeOptions: "/admin/edit-home-options",
  adminEditNews: "/admin/edit-news",
};
