//ARTWORKS CONSTANTS

export const types = {
  //ARTWORK
  FETCH_ARTWORKS: "FETCH_ARTWORKS",
  FETCH_ARTWORKS_SUCCESS: "FETCH_ARTWORKS_SUCCESS",
  FETCH_ARTWORKS_FAILURE: "FETCH_ARTWORKS_FAILURE",
  FETCH_ARTWORK_CATEGORIES: "FETCH_ARTWORK_CATEGORIES",
  FETCH_ARTWORK_CATEGORIES_SUCCESS: "FETCH_ARTWORK_CATEGORIES_SUCCESS",
  FETCH_ARTWORK_CATEGORIES_FAILURE: "FETCH_ARTWORK_CATEGORIESS_FAILURE",
  FETCH_ARTWORKS_BY_SERIE: "FETCH_ARTWORKS_BY_SERIE",
  FETCH_ARTWORKS_BY_SERIE_SUCCESS: "FETCH_ARTWORKS_BY_SERIE_SUCCESS",
  FETCH_ARTWORKS_BY_SERIE_FAILURE: "FETCH_ARTWORKS_BY_SERIE_FAILURE",
  //HOME
  UPDATE_HOME_IMAGE: "UPDATE_HOME_IMAGE",
  SET_INITIAL_EFFECT: "SET_INITIAL_EFFECT",
  //USER CONSTANT
  RECEIVE_LOGGED_USER: "RECEIVE_LOGGED_USER",

  //SIDEBAR
  RECEIVE_MENU_OPTION: "RECEIVE_MENU_OPTION",
  //CART
  RECEIVE_CREATED_CART: "RECEIVE_CREATED_CART",

  //SERIES
  FETCH_SERIES: "FETCH_SERIES",
  FETCH_SERIES_SUCCESS: "FETCH_SERIES:_SUCCESS",
  FETCH_SERIES_FAILURE: "FETCH_SERIES:_FAILURE",
};


//PRODUCTS
// FETCH_PRODUCTS: "FETCH_PRODUCTS",
// FETCH_ARTWORKS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
// FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",
// FETCH_PRODUCTS_CATEGORIES: "FETCH_PRODUCTS_CATEGORIES",
// FETCH_PRODUCTS_CATEGORIES_SUCCESS: "FETCH_PRODUCTS_CATEGORIES_SUCCESS",
// FETCH_PRODUCTS_CATEGORIES_FAILURE: "FETCH_PRODUCTS_CATEGORIESS_FAILURE",
// FETCH_PRODUCT_BY_SERIE: "FETCH_PRODUCT_BY_SERIE",
// FETCH_PRODUCT_BY_SERIE_SUCCESS: "FETCH_PRODUCT_BY_SERIE_SUCCESS",
// FETCH_PRODUCT_BY_SERIE_FAILURE: "FETCH_PRODUCT_BY_SERIE_FAILURE",
export const NAVBAR = {
  OPTIONS: [
    { NAME: "Home", id: 1, path: "/home" },
    { NAME: "About", id: 2, path: "/about" },
    { NAME: "Gallery", id: 3, path: "/gallery" },
    { NAME: "Shop", id: 4, path: "/shop/home" },
    { NAME: "Contact", id: 5, path: "/contact" },
    { NAME: "News", id: 6, path: "/news" },
  ],
  SHOPOPTIONS: [
    // { NAME: "Dolores Pardo", id: 1, path: "/home" },
    { NAME: "prints  ", id: 2, path: "prints" },
    { NAME: "small art  ", id: 3, path: "small-art"},
    { NAME: "objets  ", id: 4, path: "objets" },
    { NAME: "miscellaneous", id: 5, path: "miscellaneous" },
  ],
  ARTIST: {
    NAME: "Dolores Pardo",
  },
};


export const IMAGES = [
  { NAME: "slide8" },
  { NAME: "slide5" },
  { NAME: "slide15" },
  { NAME: "slide6" },
  { NAME: "slide3" },
  { NAME: "slide10" },
  { NAME: "slide13" },
  { NAME: "slide11" },
  { NAME: "slide12" },
  { NAME: "slide4" },
];

export const BACKGROUND_IMAGES = {
  ABOUT: "about",
  CONTACT: "contact2",
  DEFAULT: "fondo4Bis",
};

export const FOOTER = {
  RIGHTS: "All Rights Reserved",
  BACK: "Back",
};

export const PRODUCTS = {
  DESCRIPTION: "Description",
  CATEGORY: "Category",
  DATE: "Date",
  
};
