//PRODUDCT CONSTANTS

export const types = {
  //PRODUCTS
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",
  FETCH_PRODUCTS_CATEGORIES: "FETCH_PRODUCTS_CATEGORIES",
  FETCH_PRODUCTS_CATEGORIES_SUCCESS: "FETCH_PRODUCTS_CATEGORIES_SUCCESS",
  FETCH_PRODUCTS_CATEGORIES_FAILURE: "FETCH_PRODUCTS_CATEGORIESS_FAILURE",

  //PRODUCT
  FETCH_PRODUCT_BY_ID: "FETCH_PRODUCT_BY_ID",
  FETCH_PRODUCT_BY_ID_SUCCESS: "FETCH_PRODUCT_BY_ID_SUCCESS",
  FETCH_PRODUCT_BY_ID_FAILURE: "FETCH_PRODUCT_BY_ID_FAILURE",
  //HOME
  UPDATE_HOME_IMAGE: "UPDATE_HOME_IMAGE",
  SET_INITIAL_EFFECT: "SET_INITIAL_EFFECT",
  //USER CONSTANT
  RECEIVE_LOGGED_USER: "RECEIVE_LOGGED_USER",

  //SIDEBAR
  RECEIVE_MENU_OPTION: "RECEIVE_MENU_OPTION",
  //CART
  RECEIVE_CREATED_CART: "RECEIVE_CREATED_CART"
};
export const NAVBAR ={
 OPTIONS:[
  { NAME: "Home", id: 1 },
  { NAME: "About", id: 2 },
  { NAME: "Gallery", id: 3 },
  { NAME: "Shop", id: 4 },
  { NAME: "Contact", id: 5 },
  { NAME: "News", id: 6 }
],
ARTIST:{
  NAME: "Dolores Pardo"
}
}
export const IMAGES = [
  { NAME: "slide8" },
  { NAME: "slide5"},
  { NAME: "slide15" },
  { NAME: "slide6" },
  { NAME: "slide3" },
  { NAME: "slide10" },
  { NAME: "slide13" },
  { NAME: "slide11" },
  { NAME: "slide12" },
  { NAME: "slide4" },
];

export const BACKGROUND_IMAGES ={
  ABOUT:"about",
  CONTACT: "contact2",
  DEFAULT: "fondo4Bis", 

}

export const FOOTER = {
  RIGHTS: "All Rights Reserved",
  BACK: "Back"
}